import { User } from './user';

export const USERS: User[] = [
  {
    id: 1,
    email: 'alex@email.com',
    password: 'password123',
    firstName: 'Alex',
    lastName: 'Sulivan',
    country: 'Indonesia',
    city: 'Bali',
    company: 'Lithan',
    picture: '../assets/images/user/user3.png',
    banner: '../assets/images/user/banner/banner1.jpg',
  },
  {
    id: 2,
    email: 'ryan@email.com',
    password: 'password123',
    firstName: 'Ryan',
    lastName: 'Kovic',
    country: 'Indonesia',
    city: 'Jakarta',
    company: 'Google',
    picture: '../assets/images/user/user2.png',
    banner: '../assets/images/user/banner/banner2.jpg',
  },
  {
    id: 3,
    email: 'mirna@email.com',
    password: 'password123',
    firstName: 'Angelica',
    lastName: 'Mori',
    country: 'Indonesia',
    city: 'Makassar',
    company: 'Gojek',
    picture: '../assets/images/user/user1.jpg',
    banner: '../assets/images/user/banner/banner3.jpg',
  },
];
